export enum LocationType {
  WARSZAWA = 'Warszawa',
  KRAKOW = 'Kraków',
  LODZ = 'Łódź',
  GDANSK = 'Gdańsk',
  POZNAN = 'Poznań',
  WROCLAW = 'Wrocław',
  SZCZECIN = 'Szczecin',
  BYDGOSZCZ = 'BYDGOSZCZ',
  LUBLIN = 'Lublin',
  BIALYSTOK = 'BIALYSTOK',
  KATOWICE = 'Katowice',
  GDYNIA = 'Gdynia',
  RADOM = 'Radom',
  LONDON = 'London',
  KIELCE = 'Kielce',
  OLSZTYN = 'Olsztyn',
  GLIWICE = 'Gliwice',
}